title: ikeayoghurt
description: Page to collect my knowledge
remote_theme: just-the-docs

url: https://github.com/ikeayoghurt/ikeayoghurt.github.io

color_scheme: dark

aux_links:
  Template Repository: https://github.com/ikeayoghurt/ikeayoghurt.github.io
