title: ikeayoghurt
description: Page to collect my knowledge
remote_theme: just-the-docs/just-the-docs

url: https://ikeayoghurt.github.io

color_scheme: dark
permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  Template Repository: https://github.com/ikeayoghurt/ikeayoghurt.github.io
