title: ikeayoghurt
description: Page to collect my knowledge
remote_theme: just-the-docs/just-the-docs

url: https://ikeayoghurt.github.io
baseurl: ""

color_scheme: dark
permalink: pretty


aux_links:
  Github Files: https://github.com/ikeayoghurt/ikeayoghurt.github.io
